// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenTOY.Data;

#nullable disable

namespace OpenTOY.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260130221932_IphoneSupport")]
    partial class IphoneSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenTOY.Data.Entities.EmailAccountEntity", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ServiceId", "Email");

                    b.HasIndex("Id", "ServiceId");

                    b.ToTable("EmailAccounts");
                });

            modelBuilder.Entity("OpenTOY.Data.Entities.GuestAccountEntity", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("ServiceId", "DeviceId");

                    b.HasIndex("Id", "ServiceId");

                    b.ToTable("GuestAccounts");
                });

            modelBuilder.Entity("OpenTOY.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("MembershipType")
                        .HasColumnType("integer");

                    b.HasKey("Id", "ServiceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OpenTOY.Data.Entities.EmailAccountEntity", b =>
                {
                    b.HasOne("OpenTOY.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("Id", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenTOY.Data.Entities.GuestAccountEntity", b =>
                {
                    b.HasOne("OpenTOY.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("Id", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
